version: '3.8'

services:
  registry:
    build:
      context: ./registry 
    image: registry:latest
    ports:
      - "8761:8761"
    networks:
      - flexilearn-network
    restart: always

  service_user:
    build:
      context: ./service_user 
    image: service_user:latest
    depends_on:
      - registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - flexilearn-network
    restart: always

  service_exo:
    build:
      context: ./service_exo 
    image: service_exo:latest
    depends_on:
      - registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka
    ports:
      - "8082:8082"
    networks:
      - flexilearn-network
    restart: always

  gateway-service :
    build:
      context: ./gateway-service  
    image: gateway_service:latest
    depends_on:
      - registry
      - service_user
      - service_exo
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - flexilearn-network
    restart: always

networks:
  flexilearn-network:
    driver: bridge
